### PR TITLE
Basic structure and title tag added to index.html

### PR DESCRIPTION
**Pull request by OSZKAT**
Tags used
doctype 
html
head
meta
title

### CODE REVIEW

**Comment by OSZKAT** [comment]
in divs
-h1-h6
-p -parahtaph
-span - inline element
-ol +li -ordered list
-ul +li - bulleted list
-img - image added
-a -external and inetnal link (about us page created)

-

**Comment by OSZKAT** [comment]
Added script alert to index.html

**Comment by OSZKAT** [comment]
Added main and footer tags to index.html

**Comment by OSZKAT** [comment]
About us page initial content added
Styled with linked CSS

**Review by daanworks — APPROVED** [review]

**Pull request merged**
